spring.application.name=Homework_3
#spring.profiles.active=loyalty
spring.profiles.active=large-order
#spring.profiles.active=default-discount
discount.HIGH_DISCOUNT_THRESHOLD=1000.0f
discount.FIXED_DISCOUNT_AMOUNT=50.0f
discount.LOYALTY_PERCENTAGE=0.10f

spring.datasource.url=jdbc:h2:mem:ordersdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
