DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS packs CASCADE;
DROP TABLE IF EXISTS instructors CASCADE;

CREATE TABLE instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year INT NOT NULL,
    semester INT NOT NULL,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(10) NOT NULL CHECK (type IN ('COMPULSORY', 'OPTIONAL')),
    code VARCHAR(10) UNIQUE NOT NULL,
    abbr VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    group_count INT NOT NULL DEFAULT 1,
    description TEXT,

    instructor_id BIGINT,
    pack_id BIGINT,

    FOREIGN KEY (instructor_id) REFERENCES instructors(id),
    FOREIGN KEY (pack_id) REFERENCES packs(id),

    CONSTRAINT optional_course_pack_check CHECK (
     (type = 'OPTIONAL' AND pack_id IS NOT NULL) OR
     (type = 'COMPULSORY' AND pack_id IS NULL)
     )
);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    academic_year INT NOT NULL
);

CREATE TABLE student_preferences (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     student_id BIGINT NOT NULL,
     course_id BIGINT NOT NULL,
     rank INT,

     CONSTRAINT fk_student
         FOREIGN KEY(student_id) REFERENCES students(id)
             ON DELETE CASCADE,
     CONSTRAINT fk_course
         FOREIGN KEY(course_id) REFERENCES courses(id)
             ON DELETE CASCADE,

     CONSTRAINT unique_student_course UNIQUE (student_id, course_id)
);