spring.application.name=QuickGrade2

spring.kafka.bootstrap-servers=192.168.1.19:8989
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

logging.level.org.springframework.kafka=DEBUG

